---
name: autoupdate
on:
  push:
    branches:
      - main
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-24.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          MERGE_CONFLICT_ACTION: ignore
          PR_READY_STATE: ready_for_review
          MERGE_MSG: 🔀 Update branch
